- platform: history_stats
  name: Chuva Balanca Contador
  entity_id: binary_sensor.pluviometro_water_leak
  state: "off"
  type: count
  start: '{{ today_at("00:00") }}'
  end: "{{ now() }}"

# Irrigation Unlimited
- platform: average
  name: irrigation_unlimited_rain_0
  entities:
    - sensor.chuva_hoje_local
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) }}"
  end: "{{ now() }}"

- platform: average
  name: irrigation_unlimited_rain_1
  entities:
    - sensor.chuva_hoje_local
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=1) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"

- platform: average
  name: irrigation_unlimited_rain_2
  entities:
    - sensor.chuva_hoje_local
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=2) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"

- platform: average
  name: irrigation_unlimited_rain_3
  entities:
    - sensor.chuva_hoje_local
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=3) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"

- platform: average
  name: irrigation_unlimited_rain_4
  entities:
    - sensor.chuva_hoje_local
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"

- platform: average
  name: irrigation_unlimited_temperature_0
  entities:
    - sensor.termometro_servico_temperature
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) }}"
  end: "{{ now() }}"

- platform: average
  name: irrigation_unlimited_temperature_1
  entities:
    - sensor.termometro_servico_temperature
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=1) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"

- platform: average
  name: irrigation_unlimited_temperature_2
  entities:
    - sensor.termometro_servico_temperature
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=2) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"

- platform: average
  name: irrigation_unlimited_temperature_3
  entities:
    - sensor.termometro_servico_temperature
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=3) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"

- platform: average
  name: irrigation_unlimited_temperature_4
  entities:
    - sensor.termometro_servico_temperature
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"

- platform: average
  name: irrigation_unlimited_temperature_5_day_moving_average
  entities:
    - sensor.termometro_servico_temperature
  precision: 1
  start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now() }}"

#### Sensores Estação Meteorológica - LOCAL ###
## Hoje ##
- platform: average
  name: temperatura_garagem_media_hoje
  entities:
    - sensor.termometro_servico_temperature
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: average
  name: umidade_garagem_media_hoje
  entities:
    - sensor.termometro_servico_humidity
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: average
  name: pressao_garagem_media_hoje
  entities:
    - sensor.termometro_servico_pressure
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: average
  name: chuva_media_hoje
  entities:
    - sensor.chuva_hoje_local
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

## 1 Dia atrás ##
- platform: average
  name: temperatura_garagem_media_1_dia
  entities:
    - sensor.termometro_servico_temperature
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=1) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"

- platform: average
  name: umidade_garagem_media_1_dia
  entities:
    - sensor.termometro_servico_humidity
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=1) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"

- platform: average
  name: pressao_garagem_media_1_dia
  entities:
    - sensor.termometro_servico_pressure
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=1) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"

- platform: average
  name: chuva_media_1_dia
  entities:
    - sensor.chuva_hoje_local
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=1) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"

## 2 Dias atrás ##
- platform: average
  name: temperatura_garagem_media_2_dia
  entities:
    - sensor.termometro_servico_temperature
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=2) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"

- platform: average
  name: umidade_garagem_media_2_dia
  entities:
    - sensor.termometro_servico_humidity
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=2) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"

- platform: average
  name: pressao_garagem_media_2_dia
  entities:
    - sensor.termometro_servico_pressure
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=2) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"

- platform: average
  name: chuva_media_2_dia
  entities:
    - sensor.chuva_hoje_local
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=2) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"

## 3 Dias atrás ##
- platform: average
  name: temperatura_garagem_media_3_dia
  entities:
    - sensor.termometro_servico_temperature
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=3) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"

- platform: average
  name: umidade_garagem_media_3_dia
  entities:
    - sensor.termometro_servico_humidity
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=3) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"

- platform: average
  name: pressao_garagem_media_3_dia
  entities:
    - sensor.termometro_servico_pressure
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=3) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"

- platform: average
  name: chuva_media_3_dia
  entities:
    - sensor.chuva_hoje_local
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=3) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"

## 4 Dias atrás ##
- platform: average
  name: temperatura_garagem_media_4_dia
  entities:
    - sensor.termometro_servico_temperature
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"

- platform: average
  name: umidade_garagem_media_4_dia
  entities:
    - sensor.termometro_servico_humidity
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"

- platform: average
  name: pressao_garagem_media_4_dia
  entities:
    - sensor.termometro_servico_pressure
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"

- platform: average
  name: chuva_media_4_dia
  entities:
    - sensor.chuva_hoje_local
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=4) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"

## 5 Dias atrás ##
- platform: average
  name: temperatura_garagem_media_5_dia
  entities:
    - sensor.termometro_servico_temperature
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=5) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=5) }}"

- platform: average
  name: umidade_garagem_media_5_dia
  entities:
    - sensor.termometro_servico_humidity
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=5) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=5) }}"

- platform: average
  name: pressao_garagem_media_5_dia
  entities:
    - sensor.termometro_servico_pressure
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=5) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=5) }}"

- platform: average
  name: chuva_media_5_dia
  entities:
    - sensor.chuva_hoje_local
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) - timedelta(days=5) }}"
  end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=5) }}"
