automation:
  - id: restart_vscode_memory_leak
    alias: Restart VsCode Memory Leak
    trigger:
      - platform: numeric_state
        entity_id: sensor.studio_code_server_memory_percent
        above: 20
    action:
      - service: hassio.addon_restart
        data:
          addon: a0d7b954_vscode
    mode: single