homeassistant:
  enabled: true
mqtt:
  server: mqtt://a0d7b954-emqx:1883
  user: ivan
  password: ivanrsc125
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_082c58351c9dec11b4ae6a4d73138bba-if00-port0
frontend:
  enabled: true
  port: 8099
advanced:
  channel: 25
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: ISO_8601
  transmit_power: 19
device_options: {}
devices:
  '0x00124b001f918d5f':
    friendly_name: Termômetro Oficina
  '0x00158d000770dacb':
    friendly_name: PIR Corredor Externo
  '0x00158d000544a891':
    friendly_name: Cubo Sala TV
    legacy: false
  '0x60a423fffe39e61d':
    friendly_name: PIR Garagem
  '0xbc33acfffefe40ec':
    friendly_name: PIR Garagem Frente
  '0x00124b001f91d5e0':
    friendly_name: Termômetro Pergolado
  '0x00124b00251fa5d5':
    friendly_name: Termômetro Sala TV
  '0x00124b0022ebcb3e':
    friendly_name: PIR Entrada Casa
  '0x00158d0005995f6f':
    friendly_name: Janela Lavabo
  '0x60a423fffe3c57f4':
    friendly_name: PIR Lavabo
  '0x00124b0022d336f3':
    friendly_name: Porta Pergolado
  '0x00124b0022ebe0ce':
    friendly_name: Janela Cozinha
  '0x804b50fffe04731f':
    friendly_name: Sirene
  '0x00124b0024c8687f':
    friendly_name: Router Sala Fundos
  '0x00158d000758ef15':
    friendly_name: PIR Corredor Andar 2
  '0x804b50fffe08f080':
    friendly_name: Luz Escada Superior
  '0x00124b0024c2cc52':
    friendly_name: Router Suite
  '0x804b50fffeb0d5e0':
    friendly_name: Luz Varanda
  '0x00124b0024c2cc7f':
    friendly_name: Router Corredor Andar 2
  '0x804b50fffea6b587':
    friendly_name: Luz Corredor Andar 2 Fundos
  '0x54ef4410000d71ac':
    friendly_name: Lux Corredor Andar 2
  '0x00158d000758eda6':
    friendly_name: PIR Corredor Andar 2 Fundos
  '0x804b50fffe0a6a7b':
    friendly_name: Luz Serviço
  '0x804b50fffe0a6caa':
    friendly_name: Luz Garagem
  '0x00124b0022d32422':
    friendly_name: Portão Social
  '0x60a423fffe39e6b2':
    friendly_name: PIR Gás
  '0x804b50fffeb725bd':
    friendly_name: Luz Entrada Casa
  '0x00158d0004747e1c':
    friendly_name: Chovendo Agora
  '0x00124b002396fc49':
    friendly_name: Botão Externo
  '0x00124b0022cd84f7':
    friendly_name: Botão Bancada Cozinha
  '0x00158d00045a349a':
    friendly_name: Vazamento Caixa Água
  '0x00158d00062fdb26':
    friendly_name: Vazamento Telhado
  '0x00124b0022fde1c3':
    friendly_name: Botão Cozinha
  '0x00124b00257cb078':
    friendly_name: Router Telhado
  '0x04cf8cdf3c7d16ef':
    friendly_name: Lux Externo
  '0x04cf8cdf3c7d0e1e':
    friendly_name: Lux Sala TV
  '0x00124b0022d32600':
    friendly_name: Pluviômetro
  '0x00124b0022d33b3d':
    friendly_name: Porta Oficina
  '0x70ac08fffeddbb2d':
    friendly_name: mmwave cozinha
  '0xa4c138bf5622f126':
    friendly_name: Sensor Solo
  '0x70ac08fffeddb19e':
    friendly_name: mmWave Serviço
  '0x00124b00251fb081':
    friendly_name: Termômetro Suíte 2
  '0x00124b0029286db3':
    friendly_name: Janela Oficina
  '0x00124b0022ea7c47':
    friendly_name: Lava Louças Porta
  '0x00124b0022ec101f':
    friendly_name: Janela Escada
  '0x00124b0022ea78f5':
    friendly_name: Porta Entrada Casa
  '0x00124b0022670d25':
    friendly_name: Porta Garagem
  '0x00158d0006793036':
    friendly_name: Termômetro Servico
  '0x00124b001f918c53':
    friendly_name: Termômetro Suíte
  '0xa4c13861a9e82058':
    friendly_name: Vazamento Pia Cozinha
  '0xa4c138e2a7ddb9c2':
    friendly_name: Banheiro Suíte
  '0xa4c1387abb0f6625':
    friendly_name: Vazamento Lava Louças
  '0xa4c138d882c3ec02':
    friendly_name: Vazamento Lavabo
  '0xa4c13846c06fddcc':
    friendly_name: Vazamento Suíte 2
  '0x00124b0022ebde8e':
    friendly_name: Janela Quarto Fundos
  '0xf4b3b1fffeed13db':
    friendly_name: mmwave livre
  '0x00158d00075f8e73':
    friendly_name: PIR Escada Inferior
  '0xa4c138bb2ff74346':
    friendly_name: mmwave Banheiro Externo
  '0xa4c138dea39ed6a2':
    friendly_name: mmwave lavabo
  '0x00124b0022686438':
    friendly_name: Termômetro Telhado
  '0x00124b001f918a5a':
    friendly_name: Termômetro Cozinha
  '0x00124b00234e6dc1':
    friendly_name: 'Termômetro Geladeira '
  '0xa4c13805deab5437':
    friendly_name: mmwave escritorio
  '0x00158d00075f8798':
    friendly_name: PIR Escada Superior
  '0x0ceff6fffe69be7a':
    friendly_name: Termômetro Luísa
    temperature_precision: 2
  '0xa4c1389348a63af7':
    friendly_name: Porta Cozinha
  '0x00124b0022cd3ef0':
    friendly_name: Termômetro Escritório
version: 3
